 image: python:3.9

stages:
  - lint
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V  # Verificar la versió de Python
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install pylint
    - pylint $(git ls-files '*.py')

test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --cov=.

cache:
  paths:
    - .cache/pip
